# Generated by Django 4.1.3 on 2022-11-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_mesure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesure',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
